//commonjs, every file is module (by default)
//Modules - encapsulated code (only share minimum)

const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-aternative')
require('./7-mind-granade')
console.log(data)

sayHi('susan')
sayHi(names.john)
sayHi(names.peter)
sayHi(names.jack)
sayHi(names.kane)
sayHi(names.kevin)
sayHi(names.mike)